[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs_20"]

[phases.install]
cmds = [
    "cd backend && python3 -m pip install -r requirements.txt",
      "cd frontend && npm install",
        "cd frontend && npm run build"
]

[phases.build]
cmds = [
    "cd backend && python3 manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && gunicorn pe_platform.wsgi --workers 2 --bind 0.0.0.0:$PORT"